import numpy as np
import pandas as pd
drug_df = pd.read_csv('DE1_0_2008_to_2010_Prescription_Drug_Events_Sample_1.csv')
ben_df_08 = pd.read_csv('DE1_0_2008_Beneficiary_Summary_File_Sample_1.csv')
ben_df_09 = pd.read_csv('DE1_0_2009_Beneficiary_Summary_File_Sample_1.csv')
ben_df_10 = pd.read_csv('DE1_0_2010_Beneficiary_Summary_File_Sample_1.csv')
in_claims_df = pd.read_csv('DE1_0_2008_to_2010_Inpatient_Claims_Sample_1.csv')
out_claims_df = pd.read_csv('DE1_0_2008_to_2010_Outpatient_Claims_Sample_1.csv')
ben_df = ben_df_08.append(ben_df_09)
ben_df = ben_df.append(ben_df_10)
print(ben_df_08.shape)
print(ben_df_09.shape)
print(ben_df_10.shape)
print(ben_df.shape)
top_drug_df =drug_df.groupby(['PROD_SRVC_ID']).size().reset_index(name = 'count').sort_values(by = 'count',ascending = False).head(100)
selected_ids_df = pd.merge(left = drug_df, right = top_drug_df, how = 'inner', left_on = 'PROD_SRVC_ID', right_on = 'PROD_SRVC_ID')
print(selected_ids_df.shape)
print(selected_ids_df.head(10))
print(len(selected_ids_df.DESYNPUF_ID.unique()))
selected_ben = selected_ids_df.DESYNPUF_ID.unique()
ben_df.columns
print(ben_df_08[ben_df_08['DESYNPUF_ID'].isin(selected_ben)].shape)
print(ben_df_09[ben_df_09['DESYNPUF_ID'].isin(selected_ben)].shape)
print(ben_df_10[ben_df_10['DESYNPUF_ID'].isin(selected_ben)].shape)
summary_in_claims = in_claims_df[in_claims_df[u'DESYNPUF_ID'].isin(selected_ben)].groupby(by = [u'DESYNPUF_ID',u'NCH_BENE_DSCHRG_DT'])['CLM_PMT_AMT'].sum().reset_index(name = 'SUM_CLM_AMT')
summary_in_claims['year'] = summary_in_claims[u'NCH_BENE_DSCHRG_DT'].apply(lambda x: str(x)[:4])
p = summary_in_claims.plot(x = 'DESYNPUF_ID', y = 'SUM_CLM_AMT')
plt.show(p)
